### ISSUE TITLE
Satellite gives answer for itself and the base

### ISSUE THREAD

**Issue by EinfachArne** [koenvervloesem/snips-app-assistant-information#20]
Hi,

I am running a setup where I use the same assisstant on my base and and a satellite. I followed this guide: https://docs.snips.ai/articles/platform/satellites

Now if I ask the satellite for its name then it answers with the name of the base first and after that with the satellite name. This happens only with this app. Other apps only answer once.

Could this be a bug in this app or just a mistake in my setup?

**Comment by koenvervloesem** [comment]
Hi, in most setups you don't need skills/apps on your satellites, so you should install your assistant only on your base.

So you could solve this issue by removing the app Assistant Information (and any other apps you don't need on the satellite) from `/var/lib/snips/skills` or even by removing the `snips-skill-server` service on the satellite (except when you need the latter for example for a skill for the ReSpeaker leds).

Does this make sense?

**Comment by EinfachArne** [comment]
Hi,

thanks for your fast response and sorry for my late response. I was just confused because I expected, that all apps would react twice, since I installed the assistant and the skill server on the base and the satellite. Now I deinstalled skill server and assistant on my satellite and every works fine. So this issues can be closed.
